Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'MStruebing.CommandPalette:CommandPalette':
            resource: resource://MStruebing.CommandPalette/Public/CommandPalette/Plugin.js
