Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Neos.Neos.Ui.ExtensibilityExamples:WrapWithKeyboardListener':
            resource: resource://Neos.Neos.Ui.ExtensibilityExamples/Public/WrapWithKeyboardListener/Plugin.js
